### ISSUE TITLE
Unable to load addon

### ISSUE THREAD

**Issue by luiscorreal** [ellogwen/godot_ecsg_plugin#1]
Unable to load addon script from path: 'res://addons/e_csg_plugin/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/e_csg_plugin/plugin.cfg' to prevent further errors.

Godot 3.4.1 rc1

**Comment by ellogwen** [comment]
Hi, thank you for pointing this out. I am reasoning that the singleton autoload functions in kind of a wonky way.
It tries find the singleton, added via the autoload_singleton method, but fails because it cannot find the autoload file, because the plugin is not activated yet to trigger the autoload registration and there does not acrivate the plugin.

Its an open issue (https://github.com/godotengine/godot/issues/42651)

I am using a singleton as global materials store and later for an easier signal bus. I will try to fix this, in the meantime, can you add an autoload to the project name `ECSG` that points to `addons/e_csg_plugin/ecsg.gd` and then try the again? (maybe restart the editor)

![image](https://user-images.githubusercontent.com/22261975/144738017-1d681495-d0fa-42ac-83f2-910208297981.png)

**Comment by luiscorreal** [comment]
That solution works for me and I'm using that very useful addon now. Thank you!

**Comment by ellogwen** [comment]
Okay, I will fix this but first I want to make the handles work better. They are kind of rubbish right now.
I will close this issue, I left a note about this in the readme
