### ISSUE TITLE
Parametric Arch shape?

### ISSUE THREAD

**Issue by HeadClot** [ellogwen/godot_ecsg_plugin#3]
Hey bit of a feature request for the eCSG Plugin but would it be possible to get a Parametric Arch shape? 

Here is what I would like to see for the various parameters - 
1. Set how many segments the arch should have.
2. Set how big the arch should be.
3. Set the curve of the arch. 
4. Set the depth and width of the arch.

If this is possible let me know :)

**Comment by ellogwen** [comment]
Hi, already on my list :)
Will come shortly

**Comment by ellogwen** [comment]
Alright, I tinkered around a little bit yesterday, to refresh my math on parabolas and I chose to implement it with this parameters:

- Base Width (most left point to most right point)
- Thickness of the arc pillars
- Height (the highest point of the arc)
Segments (how many segments get distributed along the arc)
Distribution Ratio (how evenly the segments are spread, 0.5 is all segments are roughly same size, while closer to zero means more segments along the base and closer to one means more segments close to the tip)
Depth (How far the arc extrudes along the Z axis)

And most importantly, the arc type. I will start with Circular, Parabolic (Cubic) and Catenary for starters. I can add more later if wished, the math is basically the same, just the formula changes. Over time, I like to add architectical types as well like flat, rounded, horseshoe, three centered, inflex or ogee

Maybe I will implement the thickness as a curve, so that you can create thick bases, thin rims and thick arc tips, idk.

I will only do **symmetric** arcs/parabolas for now. Gizmos will be available as well.

Will this suite your needs @HeadClot or do you miss something importantly? Maybe I can finish this tonight, so that you can check it out tomorrow.

**Comment by HeadClot** [comment]
Sure that will work :)

**Comment by ellogwen** [comment]
@HeadClot the current main / HEAD holds a version of a parametrized arch shape with gizmos. If you want you can check it out.
I did only get the parabolic shape to work today, I will add more curves/formulas later.

The segment distribution is not done yet

**Comment by HeadClot** [comment]
> @HeadClot the current main / HEAD holds a version of a parametrized arch shape with gizmos. If you want you can check it out. I did only get the parabolic shape to work today, I will add more curves/formulas later.
> 
> The segment distribution is not done yet

Going to download it and give it a shot :)

**Comment by ellogwen** [comment]
Implemented in Alpha 3
